import type { MlPart, MlTopic } from "./mlStudyData";

export const CV_DOMAIN = "Computer Vision (CV) / Image Processing";

export interface CvTopic extends MlTopic {
  prerequisites: string[];
}

export interface CvPart extends Omit<MlPart, "topics"> {
  topics: CvTopic[];
  references: { title: string; url: string }[];
}

function topic(
  id: string,
  title: string,
  summary: string,
  keyPoints: string[],
  interviewPrompt: string,
  prerequisites: string[] = [],
): CvTopic {
  return { id, title, summary, keyPoints, interviewPrompt, prerequisites };
}

export const cvParts: CvPart[] = [
  {
    id: "images-and-signals", number: "1", title: "Images, signals, and mathematical tools",
    description: "Understand the input before choosing an algorithm: capture, tensors, uncertainty, sampling, color, and filtering.",
    color: "#4285F4", icon: "Shapes", quizQuestionCount: 0,
    references: [{ title: "OpenCV image-processing tutorials", url: "https://docs.opencv.org/4.x/d2/d96/tutorial_py_table_of_contents_imgproc.html" }],
    topics: [
      topic("image-formation", "Image formation and digital representation", "An image is a sampled measurement of light, shaped by the scene, optics, sensor, and encoding before any model sees it.", ["Exposure trades noise against motion blur; clipping destroys information.", "Separate spatial dimensions, channels, numeric range, and storage layout."], "A camera works in daylight but fails at night. What changes in the input, and which changes can software recover?"),
      topic("mathematical-tools", "Mathematical tools for reasoning about images", "Shapes, coordinate systems, and linear transformations make image operations and geometric models concrete.", ["Matrix multiplication transforms coordinates or combines features; elementwise multiplication does neither automatically.", "Homogeneous coordinates represent translation and projective transformations with matrices."], "Why can an affine translation not be represented by an ordinary 2×2 matrix?", ["image-formation"]),
      topic("noise-and-probability", "Noise, uncertainty, and essential probability", "Probability describes uncertain measurements and predictions; its essential tools explain denoising, robust fitting, and learned objectives.", ["Averages reduce independent zero-mean noise, but correlated noise survives.", "A likelihood describes observations given a cause; a posterior also incorporates a prior."], "Why does averaging frames reduce some noise but fail when objects move?", ["mathematical-tools"]),
      topic("sampling-and-pyramids", "Sampling, resizing, and image pyramids", "Resolution changes are signal-processing decisions: resampling without appropriate filtering can introduce patterns that were absent from the scene.", ["Interpolation estimates values between samples; antialiasing suppresses frequencies before downsampling.", "Pyramids trade detail for larger-scale context and efficient search."], "Why can shrinking a striped shirt produce a new pattern, and how would you prevent it?", ["image-formation"]),
      topic("color-and-contrast", "Color, intensity, and contrast transformations", "Color spaces and intensity transforms expose different information, but every transformation makes assumptions about what should be preserved.", ["RGB, grayscale, and HSV serve different purposes; OpenCV commonly decodes BGR.", "Gamma and histogram adjustment affect appearance, not missing scene information."], "When would grayscale simplify a pipeline, and when would it remove the signal you need?", ["image-formation"]),
      topic("filtering-and-restoration", "Filtering, frequency intuition, and image restoration", "Filters combine neighboring measurements to suppress noise or emphasize structure, trading robustness against detail and reconstruction uncertainty.", ["Gaussian, median, and bilateral filtering handle different noise and edge assumptions.", "Sharpening amplifies high frequencies, including noise; blur inversion is often ill-conditioned."], "Choose a filter for salt-and-pepper noise, then explain why the same choice may not be best for Gaussian sensor noise.", ["noise-and-probability", "sampling-and-pyramids"]),
    ],
  },
  {
    id: "classical-vision", number: "2", title: "Classical vision: structure, geometry, and motion",
    description: "Extract regions, establish correspondences, recover geometry, and reason about motion from image evidence.",
    color: "#34A853", icon: "Route", quizQuestionCount: 0,
    references: [{ title: "OpenCV features and matching", url: "https://docs.opencv.org/4.x/db/d27/tutorial_py_table_of_contents_feature2d.html" }, { title: "OpenCV camera geometry", url: "https://docs.opencv.org/4.x/d9/db7/tutorial_py_table_of_contents_calib3d.html" }],
    topics: [
      topic("gradients-and-edges", "Image gradients and edge detection", "Edges are rapid spatial changes, not object identities; derivatives and scale determine which changes are detected reliably.", ["Smoothing before differentiation limits noise amplification.", "Canny combines gradients, thinning, and linked weak/strong edges."], "Why does an edge detector produce many responses on a textured wall but miss a low-contrast object?", ["filtering-and-restoration"]),
      topic("regions-and-morphology", "Thresholding, morphology, and region analysis", "Thresholds create candidate regions; morphology and connected components turn those candidates into measurable shapes.", ["Adaptive thresholds handle spatial illumination changes better than one global threshold.", "Opening removes small foreground structures; closing fills small gaps."], "Build a simple pipeline for counting dark components on a bright conveyor belt and name its failure modes.", ["color-and-contrast", "filtering-and-restoration"]),
      topic("features-and-matching", "Local features, descriptors, and matching", "A useful correspondence needs both a repeatable location and a distinctive description of its neighborhood.", ["Corners constrain location in two directions; descriptors support comparison.", "SIFT uses floating-point descriptors; ORB uses binary descriptors with Hamming distance."], "Why are nearest-neighbor descriptor matches insufficient evidence that two images are aligned?", ["gradients-and-edges", "sampling-and-pyramids"]),
      topic("registration-and-ransac", "Image transformations, registration, and robust fitting", "Registration chooses a geometric model and fits it to correspondences while separating valid evidence from outliers.", ["Affine transforms preserve parallel lines; homographies model a plane or pure camera rotation.", "RANSAC repeatedly tests minimal subsets rather than trusting every match."], "Would a single homography align two views of a street with buildings at different depths?", ["features-and-matching", "mathematical-tools", "noise-and-probability"]),
      topic("camera-models", "Camera models, calibration, and coordinate frames", "A camera maps three-dimensional points into two-dimensional measurements through pose, perspective projection, and lens effects.", ["Intrinsics describe the camera; extrinsics describe its pose relative to a coordinate frame.", "Resize/crop operations change the effective pixel-coordinate calibration."], "Explain why doubling focal length changes image coordinates without moving an object in the world.", ["mathematical-tools", "registration-and-ransac"]),
      topic("stereo-and-depth", "Multiple views, stereo, and depth estimation", "Depth becomes observable through viewpoint differences, but uncertainty grows when geometric evidence is weak or ambiguous.", ["Rectified stereo reduces correspondence search to an epipolar line.", "Small disparity implies distant, uncertain depth; monocular scale requires additional information."], "Why is stereo depth much less reliable for distant objects, even with accurate cameras?", ["camera-models", "features-and-matching"]),
      topic("optical-flow", "Motion estimation and optical flow", "Optical flow estimates apparent image motion using local appearance constraints and additional spatial or learned assumptions.", ["One edge constrains only one component of motion: the aperture problem.", "Pyramids help large displacement; occlusion breaks simple brightness correspondence."], "Why is tracking a corner easier than tracking a point on a straight uniform edge?", ["gradients-and-edges", "sampling-and-pyramids"]),
    ],
  },
  {
    id: "learning-foundations", number: "3", title: "Learning foundations required for vision",
    description: "Learn only the neural-network and ML machinery needed to understand modern computer vision.",
    color: "#EA4335", icon: "TrendingDown", quizQuestionCount: 0,
    references: [{ title: "PyTorch neural-network fundamentals", url: "https://docs.pytorch.org/tutorials/beginner/basics/intro.html" }],
    topics: [
      topic("learning-and-splits", "Learning problems, baselines, and valid data splits", "Learning extracts reusable patterns from examples; a valid experiment must measure performance on genuinely independent future inputs.", ["Choose supervision and the unit of prediction before choosing a model.", "Split by subject, scene, source, or time when random image splits would leak information."], "A video-frame classifier scores 99% on a random split and fails on new videos. What went wrong?", ["image-formation", "noise-and-probability"]),
      topic("neural-networks", "Neural networks, activations, and the forward pass", "Neural networks compose learned transformations with nonlinearities to produce increasingly useful representations and task-specific outputs.", ["Without nonlinearities, stacked linear layers reduce to one linear transformation.", "The forward pass computes predictions; neither inference nor backprop alone updates weights."], "Explain what a hidden layer learns and why an activation function is necessary.", ["mathematical-tools", "learning-and-splits"]),
      topic("losses-and-probabilities", "Predictions, probabilities, and training objectives", "A training loss encodes which errors should change parameters, while output probabilities and evaluation metrics serve different roles.", ["Softmax models exclusive classes; independent sigmoids support multiple simultaneous labels.", "Cross-entropy consumes logits in PyTorch; regression losses encode different outlier penalties."], "Why should raw logits be passed to multiclass cross-entropy rather than applying softmax first?", ["neural-networks", "noise-and-probability"]),
      topic("backpropagation", "Gradients, the chain rule, and backpropagation", "Backpropagation efficiently computes how each parameter influenced the loss by composing local sensitivities through a graph.", ["Gradients have the same shapes as their parameters and add at shared branches.", "Gradient computation and optimizer updates are separate operations."], "Walk through the gradient of a two-layer network without using autograd as the explanation.", ["losses-and-probabilities"]),
      topic("optimization", "Mini-batches, optimizers, and learning-rate schedules", "Optimization balances noisy gradient estimates, step sizes, and hardware efficiency to make training converge within a budget.", ["Momentum smooths directions; adaptive optimizers also rescale coordinates.", "AdamW separates weight decay from adaptation; batch size and learning rate interact."], "Loss oscillates after increasing batch size and learning rate. What evidence would guide your next change?", ["backpropagation"]),
      topic("generalization", "Generalization, capacity, and regularization", "Generalization depends on representative evidence and appropriate capacity, not merely reducing the training objective.", ["Distinguish poor training fit from a train/validation gap before intervening.", "Weight decay, dropout, smoothing, and early stopping regularize in different ways."], "Training accuracy is excellent but validation accuracy is poor. Which interventions would you prioritize and why?", ["optimization", "learning-and-splits"]),
    ],
  },
  {
    id: "cnn-representations", number: "4", title: "Learning visual representations with CNNs",
    description: "Understand learned convolution, spatial reasoning, trainable depth, augmentation, and pretrained backbones.",
    color: "#A142F4", icon: "Layers", quizQuestionCount: 0,
    references: [{ title: "PyTorch Conv2d reference", url: "https://docs.pytorch.org/docs/stable/generated/torch.nn.Conv2d.html" }, { title: "PyTorch transfer learning for vision", url: "https://docs.pytorch.org/tutorials/beginner/transfer_learning_tutorial.html" }],
    topics: [
      topic("convolution", "Convolution and learned feature maps", "CNNs learn local reusable measurements across an image instead of assigning unrelated weights to every pixel position.", ["Sharing weights reduces parameters and introduces translation equivariance.", "Depthwise filters process channels separately; pointwise filters mix them."], "Compare the parameter counts and assumptions of a dense layer, standard convolution, and depthwise-separable convolution.", ["filtering-and-restoration", "neural-networks", "backpropagation"]),
      topic("receptive-fields", "Spatial dimensions, receptive fields, and resolution", "Kernel size, stride, padding, pooling, and dilation jointly determine what each output can see and where detail is lost.", ["Track output dimensions and input-space receptive fields separately.", "More context helps recognition, but aggressive downsampling hurts localization and small objects."], "Calculate the output shape and receptive field of two 3×3 convolutions, the first with stride two.", ["convolution", "sampling-and-pyramids"]),
      topic("residual-backbones", "Residual backbones and hierarchical visual features", "Residual paths make deep feature hierarchies easier to optimize and expose representations at several scales for later tasks.", ["An identity path lets a block learn a correction rather than reconstruct its entire input.", "Backbone stages trade spatial resolution for channels and semantic context."], "Why can adding ordinary layers worsen training error, and how does a residual connection help?", ["receptive-fields", "backpropagation"]),
      topic("normalization-and-stability", "Normalization, initialization, and gradient stability", "Stable activation and gradient scales make deep vision models trainable, with normalization behavior depending on axes and batch statistics.", ["BatchNorm uses running statistics at inference; GroupNorm and LayerNorm do not depend on other examples.", "Initialization, residual routes, and clipping address different sources of instability."], "Why might a segmentation model trained with batch size one benefit from GroupNorm rather than BatchNorm?", ["residual-backbones", "optimization"]),
      topic("augmentation", "Data augmentation and valid visual invariances", "Augmentation supplies plausible alternative observations of a labeled example, provided transformations preserve the intended prediction.", ["Boxes, masks, and keypoints must follow geometric changes to the image.", "Mixup and CutMix alter both visual evidence and training targets."], "Which augmentations would you reject for reading text or detecting left-versus-right anatomy?", ["generalization", "color-and-contrast", "receptive-fields"]),
      topic("transfer-learning", "Transfer learning and fine-tuning", "Pretraining supplies a useful starting representation, but adaptation must account for data volume, domain similarity, and which layers should change.", ["Compare frozen features, partial unfreezing, and full fine-tuning against a baseline.", "Freezing gradients does not automatically freeze BatchNorm running statistics."], "You have 500 labeled images from a new camera domain. How would you choose a fine-tuning strategy?", ["normalization-and-stability", "augmentation"]),
    ],
  },
  {
    id: "vision-tasks", number: "5", title: "Core vision tasks, objectives, and evaluation",
    description: "Connect outputs, model structure, supervision, losses, metrics, and failure modes for the major vision tasks.",
    color: "#F29900", icon: "CircleDot", quizQuestionCount: 0,
    references: [{ title: "Torchvision model families", url: "https://docs.pytorch.org/vision/stable/models.html" }, { title: "COCO evaluation implementation", url: "https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py" }],
    topics: [
      topic("classification", "Image classification and decision-making", "Image classification produces class-level decisions; the right head, metric, and operating threshold depend on which labels can coexist and which errors matter.", ["Accuracy can conceal minority-class failures; precision and recall expose different errors.", "PR curves and deployment prevalence matter when positives are rare."], "A defect classifier has 99% accuracy but misses most defects. Explain the metric failure and choose a better decision rule.", ["losses-and-probabilities", "transfer-learning"]),
      topic("detection", "Object detection: localization and prediction pipelines", "Detection predicts a variable set of labeled boxes, requiring multiscale localization, candidate construction, and duplicate handling.", ["One-stage versus two-stage and anchor-based versus anchor-free are different design axes.", "NMS uses overlap to suppress duplicate candidates but can remove adjacent real objects."], "Compare one-stage and two-stage detection for crowded scenes under a latency constraint.", ["receptive-fields", "residual-backbones", "classification"]),
      topic("detection-evaluation", "Detection training and evaluation", "A detector must learn which predictions correspond to objects and be evaluated with explicit class, overlap, and matching rules.", ["Assignment and background imbalance influence training before box losses do.", "AP integrates ranked precision/recall; mAP requires stating classes and IoU thresholds."], "AP at IoU 0.50 is strong but AP at 0.75 is poor. What does that suggest?", ["detection", "losses-and-probabilities"]),
      topic("semantic-segmentation", "Semantic segmentation and dense prediction", "Dense prediction preserves spatial correspondence while combining fine detail with global context to predict a label or value at each pixel.", ["Encoder–decoder and skip paths restore detail lost by downsampling.", "Pixel accuracy, IoU, and Dice answer different questions, especially for small foregrounds."], "Why can a segmentation model achieve high pixel accuracy while producing useless foreground masks?", ["receptive-fields", "classification", "detection"]),
      topic("instance-segmentation", "Instance and panoptic segmentation", "Instance segmentation separates individual objects; panoptic segmentation combines object identities with complete semantic scene coverage.", ["Instance masks require object separation, not just pixel classification.", "Panoptic evaluation rewards recognition and segmentation together."], "Explain the different outputs required to count people, label the road, and describe every scene pixel.", ["semantic-segmentation", "detection-evaluation"]),
      topic("pose-estimation", "Keypoints and pose estimation", "Pose prediction estimates structured locations, requiring representations and evaluation that account for visibility, object scale, and instance identity.", ["Heatmaps retain spatial uncertainty; direct coordinates produce compact outputs.", "Top-down pose inherits detector misses; bottom-up pose requires grouping joints."], "Would you use direct coordinate regression or heatmaps for small, frequently occluded joints?", ["semantic-segmentation", "detection"]),
      topic("video-and-tracking", "Video understanding and multi-object tracking", "Temporal evidence supports action recognition and persistent object identities, but these outputs require different models and evaluation.", ["Tracking combines motion prediction, gated matching, and appearance cues.", "Identity switches and long gaps can matter more than per-frame detection scores."], "Two similar people cross behind an obstruction. How would you reduce identity switches?", ["optical-flow", "detection-evaluation", "transfer-learning"]),
      topic("ocr", "Text detection and recognition", "OCR combines spatial text localization with variable-length sequence recognition, then evaluates whether the recovered text and layout are useful.", ["CTC sums monotonic alignments using a blank symbol instead of requiring character boxes.", "Character error, word error, and downstream field correctness measure different failures."], "Your OCR reads most characters correctly but extracts invoice totals incorrectly. How would you diagnose it?", ["detection", "losses-and-probabilities"]),
      topic("visual-embeddings", "Visual embeddings, similarity, and retrieval", "Visual embeddings place task-relevant similarity into a vector space that supports matching, nearest-neighbor retrieval, and anomaly baselines.", ["Training pairs and negatives define what similar means.", "Retrieval quality depends on embedding quality and index recall separately."], "Why might a classifier's features retrieve visually similar products with the wrong SKU?", ["transfer-learning", "classification", "mathematical-tools"]),
    ],
  },
  {
    id: "modern-vision", number: "6", title: "Transformers and modern vision pretraining",
    description: "Learn attention, patch-based models, self-supervision, vision–language alignment, and promptable segmentation through their reusable ideas.",
    color: "#00A6A6", icon: "Sparkles", quizQuestionCount: 0,
    references: [{ title: "Vision Transformer paper", url: "https://arxiv.org/abs/2010.11929" }, { title: "Masked Autoencoders paper", url: "https://arxiv.org/abs/2111.06377" }, { title: "CLIP paper", url: "https://arxiv.org/abs/2103.00020" }, { title: "Segment Anything paper", url: "https://arxiv.org/abs/2304.02643" }],
    topics: [
      topic("attention", "Attention and the Transformer building block", "Attention learns which representations should exchange information, using content-dependent weights rather than a fixed local neighborhood.", ["Queries ask, keys describe compatibility, and values carry the combined information.", "Attention mixing, positional information, feed-forward layers, and residual paths play distinct roles."], "Explain the shapes of Q, K, V and the attention output for a batch of image tokens.", ["visual-embeddings", "normalization-and-stability"]),
      topic("vision-transformers", "Vision Transformers and architectural tradeoffs", "Vision Transformers turn images into tokens and trade convolutional locality for flexible interactions, with patch size and attention layout controlling cost.", ["Halving patch size quadruples token count and roughly multiplies global attention-pair work by sixteen.", "Windows and hierarchical stages add locality and multiscale structure."], "Would you choose a CNN or ViT for a small dataset of high-resolution defects? State the evidence you would collect.", ["attention", "receptive-fields"]),
      topic("self-supervised-vision", "Self-supervised visual representation learning", "Self-supervision learns features from relationships or missing content in images, reducing dependence on human labels without eliminating evaluation needs.", ["Contrastive, teacher/student, and masked objectives provide different learning signals.", "Avoiding collapse is necessary but not sufficient for useful downstream representations."], "How can a model learn useful features without labels, and how would you test that claim?", ["visual-embeddings", "augmentation", "vision-transformers"]),
      topic("vision-language", "Vision–language learning and open-vocabulary recognition", "Image/text alignment supports language-defined recognition, while generative vision–language models additionally produce sequences conditioned on visual evidence.", ["Contrastive alignment enables zero-shot scores over chosen text prompts.", "A plausible generated description is not proof that a visual claim is grounded."], "Why might zero-shot image classification fail despite an apparently correct class description?", ["self-supervised-vision", "attention", "ocr"]),
      topic("promptable-segmentation", "Promptable segmentation and reusable vision models", "A reusable image encoder and prompt-conditioned mask decoder support interactive segmentation, but prompts and domain evidence still determine usefulness.", ["Cache image features when many prompts share an image.", "Mask quality, semantic identity, and downstream usefulness need separate checks."], "How would you adapt a promptable segmentation model to a new inspection domain and measure the benefit?", ["instance-segmentation", "vision-transformers"]),
    ],
  },
  {
    id: "practical-cv", number: "7", title: "Building, debugging, and operating CV systems",
    description: "Make model results trustworthy: curate data, validate inputs, diagnose failures, evaluate decisions, handle shift, and meet serving budgets.",
    color: "#E871A5", icon: "Wrench", quizQuestionCount: 0,
    references: [{ title: "PyTorch performance tuning", url: "https://docs.pytorch.org/tutorials/recipes/recipes/tuning_guide.html" }, { title: "Torchvision transforms", url: "https://docs.pytorch.org/vision/stable/transforms.html" }],
    topics: [
      topic("data-and-labels", "Data collection, annotation, and label quality", "A dataset encodes sampling and labeling decisions; improving those decisions often changes performance more than selecting a larger architecture.", ["Define ambiguous, occluded, truncated, and missing-label cases before annotation.", "Collect important failure slices and preserve an independent evaluation set."], "Annotators disagree about faint defects. How would you improve the task and dataset before training?", ["learning-and-splits", "detection-evaluation", "instance-segmentation"]),
      topic("preprocessing", "Preprocessing and input-pipeline correctness", "Training and serving must agree on image decoding, value ranges, geometry, and coordinate restoration for predictions to remain meaningful.", ["Check RGB/BGR, orientation, normalization, and model-specific resizing together.", "Preserve the transform that maps predicted coordinates back to the original image."], "The model works in a notebook but its deployed boxes are shifted. Give a prioritized investigation.", ["color-and-contrast", "sampling-and-pyramids", "augmentation", "data-and-labels"]),
      topic("training-diagnostics", "Training diagnostics, experiments, and model selection", "Controlled experiments locate the bottleneck before expensive tuning, using basic pipeline checks and evidence from training behavior.", ["Overfit a tiny clean subset to check learnability and wiring.", "Keep data, budget, and evaluation fixed when comparing models; change one hypothesis at a time."], "A new detector cannot beat the baseline. What would you check before trying a larger backbone?", ["generalization", "normalization-and-stability", "preprocessing"]),
      topic("error-analysis", "Error analysis, calibration, and reliable evaluation", "Evaluation should expose which errors happen, how confidently they happen, and whether measured gains support the intended decision.", ["Slice results by size, lighting, source, subgroup, and failure type.", "Calibration and operating thresholds differ from ranking quality; correlated samples reduce effective evidence."], "Overall AP improves but night-time performance worsens. How would you decide whether to ship?", ["classification", "detection-evaluation", "training-diagnostics"]),
      topic("domain-shift", "Domain shift, robustness, and the improvement loop", "Changing capture conditions, populations, or labels can invalidate past results, so monitoring must connect detected changes to actionable evaluations and updates.", ["Unlabeled drift signals suggest investigation, not proof of accuracy loss.", "Choose recollection, relabeling, adaptation, or retraining according to the cause."], "A factory changes cameras and false alarms rise. How would you isolate preprocessing mismatch from real domain shift?", ["error-analysis", "transfer-learning", "data-and-labels"]),
      topic("inference-and-deployment", "Inference, deployment, and resource tradeoffs", "A deployable vision system must meet end-to-end resource and quality targets, including image processing and postprocessing outside the model.", ["Profile decode, preprocessing, model, postprocessing, and transport separately.", "Measure quantization, distillation, batching, and resolution changes on important failure slices."], "A model takes 20 ms on a GPU but requests take 150 ms. How would you find and reduce the bottleneck?", ["preprocessing", "vision-transformers", "error-analysis"]),
    ],
  },
  {
    id: "interview-synthesis", number: "8", title: "Interview synthesis and final revision",
    description: "Turn the concepts into a reusable design process, work through contrasting systems, and review what to know cold.",
    color: "#7BAAF7", icon: "ListChecks", quizQuestionCount: 0,
    references: [],
    topics: [
      topic("cv-system-design", "A reusable CV system-design framework", "A strong design connects a precise product decision to evidence, model outputs, evaluation, resource constraints, and a measurable improvement loop.", ["Define the prediction unit, error costs, operating conditions, and resource budget first.", "Start with a baseline, then justify complexity using specific evidence."], "Design a vision system for detecting defects on a moving production line, starting with requirements.", ["data-and-labels", "error-analysis", "domain-shift", "inference-and-deployment"]),
      topic("design-cases", "Worked system-design cases and unfamiliar-problem reasoning", "Contrasting cases show why the same design framework produces different labels, models, metrics, and deployments under different constraints.", ["Inspection, OCR, retrieval, and tracking have different prediction units and failure costs.", "State a bottleneck and a testable intervention instead of listing every possible model."], "How would your design change when the task moves from counting objects in still images to tracking them in live video?", ["cv-system-design", "ocr", "visual-embeddings", "video-and-tracking"]),
      topic("interview-revision", "Final interview revision and common mistakes", "Review the equations, task mappings, distinctions, and design tradeoffs that allow you to explain unfamiliar vision problems from first principles.", ["Connect each formula to its assumptions and the practical effect of its variables.", "Distinguish logits/probabilities, losses/metrics, equivariance/invariance, and detection/tracking."], "Explain a CV concept in 90 seconds: intuition, mechanism, one equation, one failure mode, and one tradeoff.", ["design-cases", "vision-language", "promptable-segmentation"]),
    ],
  },
];

export const cvTopics = cvParts.flatMap((part) => part.topics);
export const cvTopicCount = cvTopics.length;
export const cvTopicsById: Record<string, CvTopic> = Object.fromEntries(cvTopics.map((t) => [t.id, t]));
export const cvPartsById: Record<string, CvPart> = Object.fromEntries(cvParts.map((p) => [p.id, p]));
export const cvPartIdForTopic: Record<string, string> = Object.fromEntries(
  cvParts.flatMap((p) => p.topics.map((t) => [t.id, p.id])),
);
export const cvLessonNumbers: Record<string, string> = Object.fromEntries(
  cvParts.flatMap((p) => p.topics.map((t, i) => [t.id, `${p.number}.${i + 1}`])),
);

export const cvReferencesByTopic: Record<string, CvPart["references"]> = {
  "camera-models": [{ title: "OpenCV camera calibration", url: "https://docs.opencv.org/4.x/dc/dbb/tutorial_py_calibration.html" }],
  "stereo-and-depth": [{ title: "OpenCV calibration and 3D reconstruction", url: "https://docs.opencv.org/4.x/d9/d0c/group__calib3d.html" }],
  "optical-flow": [{ title: "OpenCV optical flow", url: "https://docs.opencv.org/4.x/d4/dee/tutorial_optical_flow.html" }],
  "residual-backbones": [{ title: "Deep Residual Learning paper", url: "https://arxiv.org/abs/1512.03385" }, { title: "Feature Pyramid Networks paper", url: "https://arxiv.org/abs/1612.03144" }],
  "detection-evaluation": [{ title: "COCO evaluation implementation", url: "https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/cocoeval.py" }, { title: "Focal Loss paper", url: "https://arxiv.org/abs/1708.02002" }],
  "semantic-segmentation": [{ title: "U-Net paper", url: "https://arxiv.org/abs/1505.04597" }],
  "instance-segmentation": [{ title: "Panoptic Segmentation paper", url: "https://arxiv.org/abs/1801.00868" }],
  "video-and-tracking": [{ title: "HOTA tracking evaluation paper", url: "https://arxiv.org/abs/2009.07736" }],
  ocr: [{ title: "PyTorch CTC loss reference", url: "https://docs.pytorch.org/docs/stable/generated/torch.nn.CTCLoss.html" }],
  "visual-embeddings": [{ title: "FaceNet metric-learning paper", url: "https://arxiv.org/abs/1503.03832" }],
  attention: [{ title: "Attention Is All You Need", url: "https://arxiv.org/abs/1706.03762" }],
  "vision-transformers": [{ title: "Vision Transformer paper", url: "https://arxiv.org/abs/2010.11929" }],
  "self-supervised-vision": [{ title: "SimCLR paper", url: "https://arxiv.org/abs/2002.05709" }, { title: "DINO self-distillation paper", url: "https://arxiv.org/abs/2104.14294" }, { title: "Masked Autoencoders paper", url: "https://arxiv.org/abs/2111.06377" }],
  "vision-language": [{ title: "CLIP paper", url: "https://arxiv.org/abs/2103.00020" }],
  "promptable-segmentation": [{ title: "Segment Anything paper", url: "https://arxiv.org/abs/2304.02643" }],
};
