// AUTO-GENERATED by scripts/port-study-data.mjs from lib/study_data.dart.
// Ported verbatim (same ids/order) from the Flutter app's data model.

export interface StudyProblem {
  id: string;
  title: string;
  initiallyComplete?: boolean;
  difficulty?: "Easy" | "Medium" | "Hard";
  slug?: string;
  subcategory?: string;
}

export interface QuizQuestion {
  question: string;
}

export interface StudyTopic {
  slug: string;
  group: string;
  title: string;
  shortTitle: string;
  icon: string;
  color: string;
  note: string;
  problems: StudyProblem[];
  quiz?: QuizQuestion[];
}

export function leetCodeSlug(p: StudyProblem): string {
  return (
    p.slug ??
    p.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
  );
}

export function leetCodeUrl(p: StudyProblem): string {
  return `https://leetcode.com/problems/${leetCodeSlug(p)}/`;
}

export const coreStudyTopics: StudyTopic[] = [
  {
    slug: "hashmap-frequency-and-top-k",
    group: "Arrays & Hashing",
    title: "HashMap, Frequency & Top-K",
    shortTitle: "HashMap & Top-K",
    icon: "Braces",
    color: "#4285F4",
    note: "Count first, then organize. A frequency map turns repeated scans into direct lookups; a heap keeps only the best k candidates.",
    problems: [
      { id: "1", title: "Two Sum", initiallyComplete: true },
      { id: "49", title: "Group Anagrams", initiallyComplete: true },
      { id: "347", title: "Top K Frequent Elements", initiallyComplete: true },
      { id: "451", title: "Sort Characters By Frequency", initiallyComplete: true },
      { id: "295", title: "Find Median from Data Stream", initiallyComplete: true },
      { id: "23", title: "Merge K Sorted Lists", initiallyComplete: true },
      { id: "378", title: "Kth Smallest Element in a Sorted Matrix", initiallyComplete: true },
      { id: "632", title: "Smallest Range Covering Elements from K Lists", initiallyComplete: true },
    ],
    quiz: [{ question: "Walk me through your approach to Two Sum — start with the brute force, then optimize." }, { question: "You need the k most frequent elements in a stream that's too large to sort fully. What's the pattern and why not just sort?" }, { question: "Two Sum uses a hash map for O(1) lookups. What's the trade-off versus sorting the array and using two pointers?" }],
  },
  {
    slug: "sorting",
    group: "Arrays & Hashing",
    title: "Sorting",
    shortTitle: "Sorting",
    icon: "ArrowDownUp",
    color: "#8AB4F8",
    note: "For two or three groups, maintain regions with pointers. For general sorting, split, solve each half, and merge in linear time.",
    problems: [
      { id: "905", title: "Sort Array By Parity", initiallyComplete: true, subcategory: "Two-group partitioning" },
      { id: "75", title: "Sort Colors", initiallyComplete: true, subcategory: "Three-group partitioning" },
      { id: "912", title: "Sort an Array", initiallyComplete: true, subcategory: "Merge sort" },
    ],
    quiz: [{ question: "How do you decide between two-pointer partitioning and a full merge sort for a 'sort this array' question?" }, { question: "Walk through the invariant that makes the Dutch National Flag (Sort Colors) partitioning correct." }, { question: "Merge sort is O(n log n) — where does the log n come from, and why is the merge step linear?" }],
  },
  {
    slug: "sliding-window",
    group: "Scanning Patterns",
    title: "Sliding Window",
    shortTitle: "Sliding Window",
    icon: "Columns3",
    color: "#34A853",
    note: "Cue: a longest or shortest valid contiguous window. Expand the right side, then shrink from the left while the condition allows it.",
    problems: [
      { id: "3", title: "Longest Substring Without Repeating Characters", initiallyComplete: true },
      { id: "567", title: "Permutation in String", initiallyComplete: true },
      { id: "424", title: "Longest Repeating Character Replacement", initiallyComplete: true },
      { id: "76", title: "Minimum Window Substring", initiallyComplete: true },
      { id: "1358", title: "Number of Substrings Containing All Three Characters", initiallyComplete: true },
      { id: "2962", title: "Count Subarrays Where Max Element Appears at Least K Times", initiallyComplete: true },
    ],
    quiz: [{ question: "What tells you a problem is a sliding window problem rather than, say, a two-pointer or prefix-sum problem?" }, { question: "In 'Minimum Window Substring', why do you expand the right pointer and shrink the left pointer, and what invariant do you maintain?" }, { question: "How would you adapt a sliding window solution if the array can contain negative numbers, breaking the usual monotonic sum assumption?" }],
  },
  {
    slug: "two-pointers",
    group: "Scanning Patterns",
    title: "Two Pointers",
    shortTitle: "Two Pointers",
    icon: "ArrowLeftRight",
    color: "#FFD166",
    note: "Use two pointers when each comparison lets you safely discard one side of the search space.",
    problems: [
      { id: "125", title: "Valid Palindrome", initiallyComplete: true },
      { id: "15", title: "3Sum", initiallyComplete: true },
      { id: "11", title: "Container With Most Water", initiallyComplete: true },
      { id: "42", title: "Trapping Rain Water", initiallyComplete: true },
      { id: "287", title: "Find the Duplicate Number", initiallyComplete: true },
    ],
    quiz: [{ question: "For 'Container With Most Water', why do you move the pointer at the shorter line inward rather than the taller one?" }, { question: "When do two pointers require the array to be sorted first, and when do they not?" }, { question: "What's the time complexity trade-off of two pointers on a sorted array versus a hash-map approach for pair-sum problems?" }],
  },
  {
    slug: "prefix-sum-and-subarray",
    group: "Arrays & Hashing",
    title: "Prefix Sum & Subarray",
    shortTitle: "Prefix Sum",
    icon: "LineChart",
    color: "#46BDC6",
    note: "Cue: an exact subarray sum when values may be negative. Store earlier prefix sums so the needed complement becomes a lookup.",
    problems: [
      { id: "303", title: "Range Sum Query — Immutable", initiallyComplete: true },
      { id: "560", title: "Subarray Sum Equals K", initiallyComplete: true },
      { id: "523", title: "Continuous Subarray Sum", initiallyComplete: true },
      { id: "238", title: "Product of Array Except Self", initiallyComplete: true },
    ],
    quiz: [{ question: "Why does a prefix sum turn 'count subarrays with sum k' into a hash map lookup problem?" }, { question: "What edge case do people forget when initializing the prefix-sum frequency map?" }, { question: "How does prefix sum extend to 2D range-sum queries, and why is it worth it?" }],
  },
  {
    slug: "stack-and-monotonic-stack",
    group: "Scanning Patterns",
    title: "Stack & Monotonic Stack",
    shortTitle: "Stack",
    icon: "Layers",
    color: "#FBBC04",
    note: "A monotonic stack answers next or previous greater or smaller questions by removing candidates that can no longer win.",
    problems: [
      { id: "20", title: "Valid Parentheses", initiallyComplete: true },
      { id: "155", title: "Min Stack", initiallyComplete: true },
      { id: "739", title: "Daily Temperatures", initiallyComplete: true },
      { id: "503", title: "Next Greater Element II", initiallyComplete: true },
      { id: "84", title: "Largest Rectangle in Histogram", initiallyComplete: true },
    ],
    quiz: [{ question: "What invariant does a monotonic stack maintain, and what problem shape does that solve?" }, { question: "Walk through how a monotonic decreasing stack finds the next greater element for every array position." }, { question: "How is 'Largest Rectangle in Histogram' related to monotonic stacks?" }],
  },
  {
    slug: "binary-search",
    group: "Search & Optimization",
    title: "Binary Search",
    shortTitle: "Binary Search",
    icon: "Search",
    color: "#669DF6",
    note: "Exact search uses a closed range. Boundary search uses a half-open range and keeps the first position that could still satisfy the condition.",
    problems: [
      { id: "704", title: "Binary Search", initiallyComplete: true },
      { id: "35", title: "Search Insert Position", initiallyComplete: true },
      { id: "34", title: "Find First and Last Position of Element in Sorted Array", initiallyComplete: true },
      { id: "33", title: "Search in Rotated Sorted Array", initiallyComplete: true },
      { id: "153", title: "Find Minimum in Rotated Sorted Array" },
      { id: "875", title: "Koko Eating Bananas", initiallyComplete: true },
      { id: "981", title: "Time Based Key-Value Store" },
      { id: "4", title: "Median of Two Sorted Arrays" },
    ],
    quiz: [{ question: "Binary search assumes a sorted array — how do you recognize a problem where it applies even though nothing looks explicitly sorted?" }, { question: "What's the classic off-by-one bug in binary search, and how do you avoid it?" }, { question: "How does binary search adapt for a rotated sorted array, like 'Search in Rotated Sorted Array'?" }],
  },
  {
    slug: "intervals",
    group: "Scanning Patterns",
    title: "Intervals",
    shortTitle: "Intervals",
    icon: "CalendarRange",
    color: "#81C995",
    note: "Sort by end for maximum non-overlap, use a sweep line for simultaneous events, sort by start to merge, and use two pointers for intersections.",
    problems: [
      { id: "435", title: "Non-overlapping Intervals" },
      { id: "452", title: "Minimum Number of Arrows to Burst Balloons" },
      { id: "253", title: "Meeting Rooms II" },
      { id: "1094", title: "Car Pooling" },
      { id: "56", title: "Merge Intervals" },
      { id: "57", title: "Insert Interval" },
      { id: "986", title: "Interval List Intersections" },
      { id: "1229", title: "Meeting Scheduler" },
    ],
    quiz: [{ question: "What's the first step in nearly every interval-merging problem, and why does it matter so much?" }, { question: "How do you decide if two intervals overlap, and how do you merge them?" }, { question: "For 'Meeting Rooms II' — minimum number of rooms needed — why do you need both start and end events, not just merging?" }],
  },
  {
    slug: "linked-list",
    group: "Core Data Structures",
    title: "Linked List",
    shortTitle: "Linked List",
    icon: "GitBranch",
    color: "#F28B82",
    note: "Draw the links before changing them. Dummy nodes simplify head changes; slow and fast pointers reveal cycles and midpoints.",
    problems: [
      { id: "206", title: "Reverse Linked List", initiallyComplete: true },
      { id: "142", title: "Linked List Cycle II", initiallyComplete: true },
      { id: "19", title: "Remove Nth Node From End of List", initiallyComplete: true },
      { id: "143", title: "Reorder List", initiallyComplete: true },
      { id: "23", title: "Merge K Sorted Lists", initiallyComplete: true },
    ],
    quiz: [{ question: "How do you detect a cycle in a linked list without extra memory, and how do you then find where it begins?" }, { question: "Walk through reversing a singly linked list iteratively." }, { question: "How is 'Copy List with Random Pointer' harder than a normal deep copy, and what's the O(1)-space trick?" }],
  },
  {
    slug: "dfs",
    group: "DFS & Recursion",
    title: "DFS",
    shortTitle: "DFS",
    icon: "TreePine",
    color: "#78D9EC",
    note: "Use tree DFS to combine values returned by children, backtracking to explore decisions, and grid DFS to traverse connected regions.",
    problems: [
      { id: "104", title: "Maximum Depth of Binary Tree", initiallyComplete: true, subcategory: "Tree DFS" },
      { id: "98", title: "Validate Binary Search Tree", initiallyComplete: true, subcategory: "Tree DFS" },
      { id: "236", title: "Lowest Common Ancestor of a Binary Tree", initiallyComplete: true, subcategory: "Tree DFS" },
      { id: "124", title: "Binary Tree Maximum Path Sum", initiallyComplete: true, subcategory: "Tree DFS" },
      { id: "543", title: "Diameter of Binary Tree", initiallyComplete: true, subcategory: "Tree DFS" },
      { id: "46", title: "Permutations", initiallyComplete: true, subcategory: "Backtracking" },
      { id: "78", title: "Subsets", initiallyComplete: true, subcategory: "Backtracking" },
      { id: "39", title: "Combination Sum", initiallyComplete: true, subcategory: "Backtracking" },
      { id: "79", title: "Word Search", initiallyComplete: true, subcategory: "Backtracking" },
      { id: "131", title: "Palindrome Partitioning", initiallyComplete: true, subcategory: "Backtracking" },
      { id: "200", title: "Number of Islands", initiallyComplete: true, subcategory: "Flood fill / Grid DFS" },
      { id: "695", title: "Max Area of Island", initiallyComplete: true, subcategory: "Flood fill / Grid DFS" },
      { id: "130", title: "Surrounded Regions", initiallyComplete: true, subcategory: "Flood fill / Grid DFS" },
      { id: "1254", title: "Number of Closed Islands", initiallyComplete: true, subcategory: "Flood fill / Grid DFS" },
      { id: "417", title: "Pacific Atlantic Water Flow", initiallyComplete: true, subcategory: "Flood fill / Grid DFS" },
    ],
    quiz: [{ question: "When would you reach for DFS over BFS on a tree or graph problem?" }, { question: "How do you handle a grid flood-fill / island-counting DFS without risking a stack overflow on very large grids?" }, { question: "For backtracking problems like generating permutations or subsets, what makes the difference between DFS and plain recursion explicit?" }],
  },
  {
    slug: "bfs",
    group: "Graph Algorithms",
    title: "BFS",
    shortTitle: "BFS",
    icon: "Share2",
    color: "#5BB9D4",
    note: "BFS explores one layer at a time. Use it for tree levels and unweighted shortest paths; Kahn’s algorithm applies the same queue pattern to dependencies.",
    problems: [
      { id: "102", title: "Binary Tree Level Order Traversal", initiallyComplete: true, subcategory: "Tree BFS" },
      { id: "207", title: "Course Schedule", initiallyComplete: true, subcategory: "Topological sort" },
      { id: "1857", title: "Largest Color Value in a Directed Graph", initiallyComplete: true, subcategory: "Topological sort" },
      { id: "1091", title: "Shortest Path in Binary Matrix", initiallyComplete: true, subcategory: "Shortest path" },
      { id: "542", title: "01 Matrix", initiallyComplete: true, subcategory: "Shortest path" },
      { id: "433", title: "Minimum Genetic Mutation", initiallyComplete: true, subcategory: "Shortest path" },
      { id: "909", title: "Snakes and Ladders", initiallyComplete: true, subcategory: "Shortest path" },
      { id: "1293", title: "Shortest Path in a Grid with Obstacles Elimination", initiallyComplete: true, subcategory: "Shortest path" },
      { id: "847", title: "Shortest Path Visiting All Nodes", subcategory: "Shortest path" },
    ],
    quiz: [{ question: "Why is BFS the right tool for shortest path in an unweighted graph, but not in a weighted one?" }, { question: "Walk through multi-source BFS and give an example of when it's needed." }, { question: "How do you detect a cycle in a directed graph using BFS, and how does that relate to topological sort?" }],
  },
  {
    slug: "dijkstra-and-weighted-graphs",
    group: "Graph Algorithms",
    title: "Dijkstra & Weighted Graphs",
    shortTitle: "Dijkstra",
    icon: "Route",
    color: "#7BAAF7",
    note: "Keep the best known cumulative cost and use a min-heap for the next state. Relax an edge only when it improves that cost.",
    problems: [
      { id: "1514", title: "Path with Maximum Probability", initiallyComplete: true },
      { id: "1631", title: "Path With Minimum Effort", initiallyComplete: true },
      { id: "787", title: "Cheapest Flights Within K Stops", initiallyComplete: true },
      { id: "3341", title: "Find Minimum Time to Reach Last Room I", initiallyComplete: true },
    ],
    quiz: [{ question: "Why does Dijkstra's algorithm fail on graphs with negative edge weights?" }, { question: "What data structure makes Dijkstra's algorithm efficient, and what's the resulting complexity?" }, { question: "How would you adapt Dijkstra to also reconstruct the actual shortest path, not just its length?" }],
  },
  {
    slug: "union-find-and-mst",
    group: "Graph Algorithms",
    title: "Union Find & MST",
    shortTitle: "Union Find",
    icon: "Combine",
    color: "#66C2A5",
    note: "Each set points to a representative root. Path compression speeds up find; Kruskal sorts edges and unions until n − 1 edges connect the graph.",
    problems: [
      { id: "547", title: "Number of Provinces", initiallyComplete: true },
      { id: "990", title: "Satisfiability of Equality Equations", initiallyComplete: true },
      { id: "1584", title: "Min Cost to Connect All Points", initiallyComplete: true },
    ],
    quiz: [{ question: "What do path compression and union by rank/size each contribute to Union-Find's efficiency?" }, { question: "Why is Union-Find the natural structure for 'number of connected components' or 'redundant connection' problems?" }, { question: "Walk through Kruskal's algorithm for minimum spanning tree and explain where Union-Find comes in." }],
  },
  {
    slug: "greedy",
    group: "Search & Optimization",
    title: "Greedy",
    shortTitle: "Greedy",
    icon: "TrendingUp",
    color: "#FFC857",
    note: "Make the locally safe choice and state why it cannot hurt a future decision. The proof matters as much as the implementation.",
    problems: [
      { id: "53", title: "Maximum Subarray", initiallyComplete: true },
      { id: "55", title: "Jump Game", initiallyComplete: true },
      { id: "45", title: "Jump Game II", initiallyComplete: true },
      { id: "134", title: "Gas Station", initiallyComplete: true },
    ],
    quiz: [{ question: "How do you tell whether a problem actually has the greedy-choice property, versus needing DP?" }, { question: "For 'Jump Game II' (minimum jumps to reach the end), what's the greedy insight?" }, { question: "In interval scheduling — maximizing the number of non-overlapping intervals you can select — why does sorting by end time (not start time) give the greedy optimum?" }],
  },
  {
    slug: "trie",
    group: "Core Data Structures",
    title: "Trie",
    shortTitle: "Trie",
    icon: "Network",
    color: "#CE93D8",
    note: "Walk one character per level. Store terminal markers separately from children so prefixes and complete words remain distinct.",
    problems: [
      { id: "208", title: "Implement Trie (Prefix Tree)", initiallyComplete: true },
      { id: "211", title: "Design Add and Search Words Data Structure" },
    ],
    quiz: [{ question: "What's the time complexity advantage a trie gives you over a hash set of strings for prefix queries?" }, { question: "How is a trie node typically structured, and how do you mark the end of a word?" }, { question: "When would a trie be the wrong choice compared to a simpler hash set, even for prefix problems?" }],
  },
  {
    slug: "data-structures-to-know",
    group: "Core Data Structures",
    title: "Data Structures to Know",
    shortTitle: "Data Structures",
    icon: "CircuitBoard",
    color: "#A7C7FA",
    note: "Start with the operations and their target complexity, then combine structures so each operation has exactly the information it needs.",
    problems: [
      { id: "146", title: "LRU Cache", initiallyComplete: true },
      { id: "380", title: "Insert Delete GetRandom O(1)", initiallyComplete: true, slug: "insert-delete-getrandom-o1" },
    ],
    quiz: [{ question: "'Insert Delete GetRandom O(1)' asks for average O(1) insert, delete, and random access all at once — why doesn't a plain hash set or array alone satisfy that?" }, { question: "When would you reach for a heap versus a balanced BST when you need ordered access to a dynamic set?" }, { question: "What's the core design idea behind an LRU cache, and which two structures does it combine?" }],
  },
];

export const challengeTopics: StudyTopic[] = [
  {
    slug: "mixed-leetcode-challenge-set-round-4",
    group: "Challenge Rounds",
    title: "Mixed LeetCode Challenge Set — Round 4",
    shortTitle: "Round 4",
    icon: "Flag",
    color: "#FF8A65",
    note: "A compact mixed round spanning search, graphs, trees, stacks, tries, and array techniques.",
    problems: [
      { id: "1102", title: "Path With Maximum Minimum Value", initiallyComplete: true, difficulty: "Medium" },
      { id: "151", title: "Reverse Words in a String", initiallyComplete: true, difficulty: "Medium" },
      { id: "378", title: "Kth Smallest Element in a Sorted Matrix", initiallyComplete: true, difficulty: "Medium" },
      { id: "103", title: "Binary Tree Zigzag Level Order Traversal", initiallyComplete: true, difficulty: "Medium" },
      { id: "678", title: "Valid Parenthesis String", initiallyComplete: true, difficulty: "Medium" },
      { id: "646", title: "Maximum Length of Pair Chain", initiallyComplete: true, difficulty: "Medium" },
      { id: "48", title: "Rotate Image", initiallyComplete: true, difficulty: "Medium" },
      { id: "1857", title: "Largest Color Value in a Directed Graph", initiallyComplete: true, difficulty: "Hard" },
      { id: "75", title: "Sort Colors", initiallyComplete: true, difficulty: "Medium" },
      { id: "297", title: "Serialize and Deserialize Binary Tree", initiallyComplete: true, difficulty: "Hard" },
      { id: "1019", title: "Next Greater Node In Linked List", initiallyComplete: true, difficulty: "Medium" },
      { id: "410", title: "Split Array Largest Sum", initiallyComplete: true, difficulty: "Hard" },
      { id: "1358", title: "Number of Substrings Containing All Three Characters", initiallyComplete: true, difficulty: "Medium" },
      { id: "912", title: "Sort an Array", initiallyComplete: true, difficulty: "Medium" },
      { id: "677", title: "Map Sum Pairs", initiallyComplete: true, difficulty: "Medium" },
      { id: "287", title: "Find the Duplicate Number", initiallyComplete: true, difficulty: "Medium" },
      { id: "815", title: "Bus Routes", initiallyComplete: true, difficulty: "Hard" },
      { id: "73", title: "Set Matrix Zeroes", initiallyComplete: true, difficulty: "Medium" },
      { id: "1101", title: "The Earliest Moment When Everyone Become Friends", initiallyComplete: true, difficulty: "Medium" },
      { id: "235", title: "Lowest Common Ancestor of a Binary Search Tree", initiallyComplete: true, difficulty: "Medium" },
    ],
  },
  {
    slug: "mixed-leetcode-challenge-set-round-3",
    group: "Challenge Rounds",
    title: "Mixed LeetCode Challenge Set — Round 3",
    shortTitle: "Round 3",
    icon: "Flag",
    color: "#CE93D8",
    note: "A broad mixed round with extra interval scheduling, traversal, graph, and design practice.",
    problems: [
      { id: "1642", title: "Furthest Building You Can Reach", initiallyComplete: true, difficulty: "Medium" },
      { id: "886", title: "Possible Bipartition", initiallyComplete: true, difficulty: "Medium" },
      { id: "394", title: "Decode String", initiallyComplete: true, difficulty: "Medium" },
      { id: "1482", title: "Minimum Number of Days to Make m Bouquets", initiallyComplete: true, difficulty: "Medium" },
      { id: "77", title: "Combinations", initiallyComplete: true, difficulty: "Medium" },
      { id: "1448", title: "Count Good Nodes in Binary Tree", initiallyComplete: true, difficulty: "Medium" },
      { id: "904", title: "Fruit Into Baskets", initiallyComplete: true, difficulty: "Medium" },
      { id: "947", title: "Most Stones Removed with Same Row or Column", initiallyComplete: true, difficulty: "Medium" },
      { id: "24", title: "Swap Nodes in Pairs", initiallyComplete: true, difficulty: "Medium" },
      { id: "1976", title: "Number of Ways to Arrive at Destination", initiallyComplete: true, difficulty: "Medium" },
      { id: "1334", title: "Find the City With the Smallest Number of Neighbors at a Threshold Distance", initiallyComplete: true, difficulty: "Medium" },
      { id: "2662", title: "Minimum Cost of a Path With Special Roads", initiallyComplete: true, difficulty: "Medium" },
      { id: "1368", title: "Minimum Cost to Make at Least One Valid Path in a Grid", initiallyComplete: true, difficulty: "Hard" },
      { id: "3112", title: "Minimum Time to Visit Disappearing Nodes", initiallyComplete: true, difficulty: "Medium" },
      { id: "1024", title: "Video Stitching", initiallyComplete: true, difficulty: "Medium" },
      { id: "648", title: "Replace Words", initiallyComplete: true, difficulty: "Medium" },
      { id: "1268", title: "Search Suggestions System", initiallyComplete: true, difficulty: "Medium" },
      { id: "721", title: "Accounts Merge", initiallyComplete: true, difficulty: "Medium" },
      { id: "1061", title: "Lexicographically Smallest Equivalent String", initiallyComplete: true, difficulty: "Medium" },
      { id: "1584", title: "Min Cost to Connect All Points", initiallyComplete: true, difficulty: "Medium" },
      { id: "1168", title: "Optimize Water Distribution in a Village", initiallyComplete: true, difficulty: "Hard" },
      { id: "2958", title: "Length of Longest Subarray With at Most K Frequency", initiallyComplete: true, difficulty: "Medium" },
      { id: "921", title: "Minimum Add to Make Parentheses Valid", initiallyComplete: true, difficulty: "Medium" },
      { id: "122", title: "Best Time to Buy and Sell Stock II", initiallyComplete: true, difficulty: "Medium" },
      { id: "735", title: "Asteroid Collision", initiallyComplete: true, difficulty: "Medium" },
      { id: "2462", title: "Total Cost to Hire K Workers", initiallyComplete: true, difficulty: "Medium" },
      { id: "1110", title: "Delete Nodes And Return Forest", initiallyComplete: true, difficulty: "Medium" },
      { id: "162", title: "Find Peak Element", initiallyComplete: true, difficulty: "Medium" },
      { id: "40", title: "Combination Sum II", initiallyComplete: true, difficulty: "Medium" },
      { id: "90", title: "Subsets II", initiallyComplete: true, difficulty: "Medium" },
      { id: "328", title: "Odd Even Linked List", initiallyComplete: true, difficulty: "Medium" },
      { id: "863", title: "All Nodes Distance K in Binary Tree", initiallyComplete: true, difficulty: "Medium" },
      { id: "1396", title: "Design Underground System", initiallyComplete: true, difficulty: "Medium" },
      { id: "763", title: "Partition Labels", initiallyComplete: true, difficulty: "Medium" },
      { id: "2812", title: "Find the Safest Path in a Grid", initiallyComplete: true, difficulty: "Medium" },
      { id: "1146", title: "Snapshot Array", initiallyComplete: true, difficulty: "Medium" },
      { id: "211", title: "Design Add and Search Words Data Structure", initiallyComplete: true, difficulty: "Medium" },
    ],
  },
  {
    slug: "mixed-leetcode-challenge-set-round-2",
    group: "Challenge Rounds",
    title: "Mixed LeetCode Challenge Set — Round 2",
    shortTitle: "Round 2",
    icon: "Flag",
    color: "#46BDC6",
    note: "A mixed review of matrices, graphs, heaps, intervals, linked lists, and scanning patterns.",
    problems: [
      { id: "2658", title: "Maximum Number of Fish in a Grid", initiallyComplete: true, difficulty: "Medium" },
      { id: "199", title: "Binary Tree Right Side View", initiallyComplete: true, difficulty: "Medium" },
      { id: "74", title: "Search a 2D Matrix", initiallyComplete: true, difficulty: "Medium" },
      { id: "399", title: "Evaluate Division", initiallyComplete: true, difficulty: "Medium" },
      { id: "767", title: "Reorganize String", initiallyComplete: true, difficulty: "Medium" },
      { id: "930", title: "Binary Subarrays With Sum", initiallyComplete: true, difficulty: "Medium" },
      { id: "881", title: "Boats to Save People", initiallyComplete: true, difficulty: "Medium" },
      { id: "1011", title: "Capacity To Ship Packages Within D Days", initiallyComplete: true, difficulty: "Medium" },
      { id: "2", title: "Add Two Numbers", initiallyComplete: true, difficulty: "Medium" },
      { id: "85", title: "Maximal Rectangle", initiallyComplete: true, difficulty: "Hard" },
      { id: "851", title: "Loud and Rich", initiallyComplete: true, difficulty: "Medium" },
      { id: "729", title: "My Calendar I", initiallyComplete: true, difficulty: "Medium" },
      { id: "1162", title: "As Far from Land as Possible", initiallyComplete: true, difficulty: "Medium" },
      { id: "138", title: "Copy List with Random Pointer", initiallyComplete: true, difficulty: "Medium" },
      { id: "2050", title: "Parallel Courses III", initiallyComplete: true, difficulty: "Hard" },
      { id: "454", title: "4Sum II", initiallyComplete: true, difficulty: "Medium" },
      { id: "436", title: "Find Right Interval", initiallyComplete: true, difficulty: "Medium" },
      { id: "1004", title: "Max Consecutive Ones III", initiallyComplete: true, difficulty: "Medium" },
      { id: "437", title: "Path Sum III", initiallyComplete: true, difficulty: "Medium" },
      { id: "373", title: "Find K Pairs with Smallest Sums", initiallyComplete: true, difficulty: "Medium" },
      { id: "167", title: "Two Sum II — Input Array Is Sorted", initiallyComplete: true, difficulty: "Medium" },
      { id: "1926", title: "Nearest Exit from Entrance in Maze", initiallyComplete: true, difficulty: "Medium" },
      { id: "907", title: "Sum of Subarray Minimums", initiallyComplete: true, difficulty: "Medium" },
      { id: "1129", title: "Shortest Path with Alternating Colors", initiallyComplete: true, difficulty: "Medium" },
      { id: "36", title: "Valid Sudoku", initiallyComplete: true, difficulty: "Medium" },
      { id: "713", title: "Subarray Product Less Than K", initiallyComplete: true, difficulty: "Medium" },
      { id: "304", title: "Range Sum Query 2D — Immutable", initiallyComplete: true, difficulty: "Medium" },
    ],
  },
  {
    slug: "mixed-leetcode-challenge-set-round-1",
    group: "Challenge Rounds",
    title: "Mixed LeetCode Challenge Set — Round 1",
    shortTitle: "Round 1",
    icon: "Flag",
    color: "#81C995",
    note: "The original mixed round, covering core array, graph, tree, heap, stack, and interval patterns.",
    problems: [
      { id: "128", title: "Longest Consecutive Sequence", initiallyComplete: true, difficulty: "Medium" },
      { id: "973", title: "K Closest Points to Origin", initiallyComplete: true, difficulty: "Medium" },
      { id: "934", title: "Shortest Bridge", initiallyComplete: true, difficulty: "Medium" },
      { id: "153", title: "Find Minimum in Rotated Sorted Array", initiallyComplete: true, difficulty: "Medium" },
      { id: "525", title: "Contiguous Array", initiallyComplete: true, difficulty: "Medium" },
      { id: "16", title: "3Sum Closest", initiallyComplete: true, difficulty: "Medium" },
      { id: "230", title: "Kth Smallest Element in a BST", initiallyComplete: true, difficulty: "Medium" },
      { id: "209", title: "Minimum Size Subarray Sum", initiallyComplete: true, difficulty: "Medium" },
      { id: "92", title: "Reverse Linked List II", initiallyComplete: true, difficulty: "Medium" },
      { id: "1034", title: "Coloring A Border", initiallyComplete: true, difficulty: "Medium" },
      { id: "310", title: "Minimum Height Trees", initiallyComplete: true, difficulty: "Medium" },
      { id: "692", title: "Top K Frequent Words", initiallyComplete: true, difficulty: "Medium" },
      { id: "22", title: "Generate Parentheses", initiallyComplete: true, difficulty: "Medium" },
      { id: "974", title: "Subarray Sums Divisible by K", initiallyComplete: true, difficulty: "Medium" },
      { id: "981", title: "Time Based Key-Value Store", initiallyComplete: true, difficulty: "Medium" },
      { id: "402", title: "Remove K Digits", initiallyComplete: true, difficulty: "Medium" },
      { id: "864", title: "Shortest Path to Get All Keys", initiallyComplete: true, difficulty: "Hard" },
      { id: "1094", title: "Car Pooling", initiallyComplete: true, difficulty: "Medium" },
      { id: "1219", title: "Path with Maximum Gold", initiallyComplete: true, difficulty: "Medium" },
      { id: "452", title: "Minimum Number of Arrows to Burst Balloons", initiallyComplete: true, difficulty: "Medium" },
      { id: "105", title: "Construct Binary Tree from Preorder and Inorder Traversal", initiallyComplete: true, difficulty: "Medium" },
      { id: "992", title: "Subarrays with K Different Integers", difficulty: "Hard" },
      { id: "18", title: "4Sum", initiallyComplete: true, difficulty: "Medium" },
      { id: "827", title: "Making A Large Island", initiallyComplete: true, difficulty: "Hard" },
      { id: "2192", title: "All Ancestors of a Node in a Directed Acyclic Graph", initiallyComplete: true, difficulty: "Medium" },
      { id: "25", title: "Reverse Nodes in k-Group", initiallyComplete: true, difficulty: "Hard" },
      { id: "901", title: "Online Stock Span", initiallyComplete: true, difficulty: "Medium" },
      { id: "1834", title: "Single-Threaded CPU", initiallyComplete: true, difficulty: "Medium" },
    ],
  },
];

export const studyTopics: StudyTopic[] = [...coreStudyTopics, ...challengeTopics];

export const coreProblemIds: Set<string> = new Set(
  coreStudyTopics.flatMap((topic) => topic.problems.map((p) => p.id))
);

export const initialCompletedProblems: Set<string> = new Set(
  studyTopics.flatMap((topic) => topic.problems.filter((p) => p.initiallyComplete).map((p) => p.id))
);

export const uniqueProblems: StudyProblem[] = (() => {
  const byId = new Map<string, StudyProblem>();
  for (const topic of studyTopics) {
    for (const problem of topic.problems) {
      if (!byId.has(problem.id)) byId.set(problem.id, problem);
    }
  }
  return [...byId.values()];
})();

export const studyTopicsBySlug: Record<string, StudyTopic> = Object.fromEntries(
  studyTopics.map((t) => [t.slug, t])
);
